spring:
  profiles:
    active:
    - redis

---
spring:
  profiles: redis
  application:
    name: luohao-config-redis
    
---
spring:
  profiles: mybatis
  application:
    name: luohao-config-mybatis
    #测试
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
    
